### ISSUE TITLE
Custom filenames

### ISSUE THREAD

**Issue by pxwise** [BlessCSS/grunt-bless#12]
Could there be an option to output the filenames with a user configurable pattern other than myfilename-blessed1.css?

**Comment by matt-bailey** [comment]
+1 - It would be nice to have the option to modify "-blessed1".

However, by upstream project I assume you mean the actual 'bless' dependency, so I guess you don't have direct control over this.

**Comment by pixelkritzel** [comment]
+1

**Comment by mtscout6** [comment]
We'd be open to a pull request in the upstream bless project to make that configurable.

**Comment by mtscout6** [comment]
Actually I'm pretty sure that the new v4 changes there allow you set the file names yourself.

**Comment by mayacode** [comment]
As I'm not able to set names by myself, I created simple copy subtask in grunt, maybe this will help others who're facing the same problem:

    bless: {
        files: [{expand: true, cwd: '<%= paths.theme.css %>', src: ['blessedmain*.css'], dest: '<%= paths.theme.css %>',
        rename: function(dest, src){
          var number = 0;
          if (src.indexOf('-blessed') !== -1) {
            number = src.split('-blessed')[1].split('.')[0];
          }
          return dest + '/' + 'main-ie' + number + '.min.css';
        }}]
      }

**Comment by AaronAsAChimp** [comment]
This feature has been implemented and released in grunt-bless v1.0.0
