### ISSUE TITLE
Conflict flags in bless.js.orig

### ISSUE THREAD

**Issue by mimiflynn** [BlessCSS/grunt-bless#27]
Discovered the following after running `npm install grunt-bless` in `tasks/bless.js.orig`:

Line 125
```
<<<<<<< HEAD
                        grunt.log.writeln('File ' + chalk.cyan(file.filename) + ' ' + lastSentence + '.');
                    }
				});
=======
							grunt.log.writeln('File ' + chalk.cyan(file.filename) + ' ' + lastSentence + '.');
						}
					});
>>>>>>> Fix merge issues, clean up white space.
```
Not seeing this file in the repo here, though.

**Comment by AaronAsAChimp** [comment]
The file `tasks/bless.js.orig` is a junk file and shouldn't be executed. I'll add this to the ignores to keep things clean.

**Comment by aabenoja** [comment]
Close?
