### ISSUE TITLE
Bless v4.0.0-alpha.0 is out

### ISSUE THREAD

**Issue by mtscout6** [BlessCSS/grunt-bless#28]
We just pushed v4.0.0-alpha.0 to npm today! Please let us know how it works for you so we can be confident about getting the actual release out. Also, the Bless project has a new home at https://github.com/BlessCSS/bless. Since it is now in a github organization we'd also like to extend the invitation to transfer this repo there and add you as a member of the organization. The goal being to consolidate and document bless and it's usage with different build tools. Our main focus will be towards Gulp, Grunt, Webpack, and possibly Browserify. If you have any questions feel free to reach out in our issue log or hit us up on gitter at https://gitter.im/BlessCSS/bless

**Comment by AaronAsAChimp** [comment]
Thanks, I've updated the 1.0-dev branch to work with the alpha. Seeing as this project was originally a pull request to bless, it would be fitting to once again rejoin it. :)

**Comment by mtscout6** [comment]
Sounds great I added you to the organization, you should see an email from github about it. Here are the instructions for transferring the repo to the org: https://help.github.com/articles/transferring-a-repository/.

Once you're there we also have gitter setup for instant chat about things. Check out: https://gitter.im/BlessCSS/bless

**Comment by AaronAsAChimp** [comment]
Done and transferred!
