### ISSUE TITLE
Warning: Cannot read property 'reduce' of undefined Use --force to continue.

### ISSUE THREAD

**Issue by markdhel** [BlessCSS/grunt-bless#33]
It throws **Warning: Cannot read property 'reduce' of undefined Use --force to continue.** error if the source CSS has charset rule ,

`@charset "UTF-8";
body {
  margin: 0; }
`
Can you advise? thanks.

**Comment by AaronAsAChimp** [comment]
Thanks for the issue. This appears to be a bug in the upstream project. It can be tracked in this ticket, BlessCSS/bless#93.
