### ISSUE TITLE
0

### ISSUE THREAD

**Issue by san4osq** [BlessCSS/grunt-bless#34]

**Comment by AaronAsAChimp** [comment]
Thanks for the feature request. Can you please provide a use case? Is it absolute filesystem path (as in /home/user/website/css/styles.css), or an absolute URL (as in http://example.com/css/styles.css)?

**Comment by san4osq** [comment]
ok, I'm not sure, because I mean
@import "D:/www/styles/style1.css" -> absolute path
@import "style1.css"                        -> relative path

**Comment by san4osq** [comment]
Can you improve this functionality?

**Comment by AaronAsAChimp** [comment]
I'm assuming because you removed all the content from this issue, its not longer valid. Closing.

**Comment by san4osq** [comment]
https://github.com/BlessCSS/grunt-bless/issues/35
