### ISSUE TITLE
Use grunt-banner if you want to add a banner

### ISSUE THREAD

**Issue by pixeldrew** [BlessCSS/grunt-bless#40]
Banner option is pointless

**Comment by AaronAsAChimp** [comment]
There are several reasons why the banner option was added:
1. Parity with other grunt post-processors.
2. Allowing the user to easily put a banner at the top of the main file. Without this feature all comments at the top of the original file end up in the last file.
3. Additional plugins negatively affects Grunt's performance. The banner feature adds a trivial amount of complexity to this plugin, so its a performance gain for most users.

You are not required to use this feature. If another banner plugin suits your needs then use it.
