### ISSUE TITLE
@media statements that include rules with comments are being dropped in generated blessed files 

### ISSUE THREAD

**Issue by Askelkana** [BlessCSS/grunt-bless#6]
Any @media sections that contain rules that themselves contain comments have the beginning @media rule dropped (but not the closing brace!). You can imagine how problematic this is for designing responsive stylesheets.

Of course, if the input stylesheets are clean then bless works just fine. So this isn't a blocker, by any means.

**Comment by AaronAsAChimp** [comment]
This feature has been implemented and released in grunt-bless v1.0.0
